### ISSUE TITLE
Occasional edit level mismatch in AcceptChanges

### ISSUE THREAD

**Issue by michaelcsikos** [MarimerLLC/cslaforum#409]
Hi Rocky, Jonny, et al

In a WinForms project I still get the occasional `UndoException`. I'm finding it practically impossible to reproduce and debug, but I have received bug reports from my client with screencaps. I am following the recommended approach for binding, unbinding, saving and rebinding. It's a reasonably complicated form with sort and filter columns and several child binding sources.

I noticed that in the CslaContrib project `SuspendBinding()` and `ResumeBinding()` are called. Could that make any difference?

If it's a random WinForms binding problem, is there any way to prevent an `UndoExceptoion` by trawling the object graph and forcing an `EndEdit()` where necessary?

Thanks for your advice.

**Comment by tfreitasleal** [comment]
Hi Michael,
I think you are refering to CslaContrib's BindingSourceExtensions. A few months ago, I published [CslaExtremeDemos](https://github.com/tfreitasleal/CslaExtremeDemos) to explore/test some less usual Csla scenarios. I can't remember the exact details but I found some issues using CslaContrib's BindingSourceExtensions. So I ended up testing a changed version you can find on 
`...\Source\CslaExtremeDemos.WindowsForms` folder.

**Comment by jonnybee** [comment]
It is a tricky situation to debug. Which version of CSLA are you using? 

The challenge is to find out where and how there is a child item that is still beeing edited. 

You _could_ make a special debug window that inspects the object graph and show/highlight the objects that have EditLevel > 0. THis would at least hopefully identify the objects/list that is the culprit.

**Comment by GillesBer** [comment]
We also had lot/and still have some sporadic issues on our Winform app.
In order to diagnose it, we fork the CSLA code base, adding additional child/parent editLevel and child/parent descriptions.
Note: The last releases (CSLA 4.6.600) already improves diagnosis with the child/parent editLevel .

In Csla.Share\Core\UndoException.cs
public UndoException(string message, string typeName, string parentTypeName, int currentEditLevel, int expectedEditLevel, string objectDescription, string parentObjectDescription)

I personally use ToString() to populate the description.
I did not propose it as a PR, but might be I should.

**Comment by tfreitasleal** [comment]
Hi GillesBeer,

This is a very difficult area to diagnose. I had some hard experiences on another project, because I wasn't using BindingSource objects (I was binding directly to CSLA objects/lists). If your code improves diagnosis over CSLA 4.6.603, I think a PR is welcome.

**Comment by michaelcsikos** [comment]
Thank you all for your responses. In a way, I'm glad I'm not the only way wrestling with these issues with WinForms. Tiago, I have downloaded your extreme demos and had a look. I am currently using CSLA 4.6.500. I plan to update in the near future. The extra info will help. Jonny, I'll make a debug window, too.
