### ISSUE TITLE
Missing WPF packages in ProjectTracker

### ISSUE THREAD

**Issue by BlagoCuljak** [MarimerLLC/cslaforum#805]
I just can't start new V5 version, tried on multiple computers and VS versions.
![CSLANuget](https://user-images.githubusercontent.com/34435929/64349420-397ee500-cff7-11e9-9599-eba24f06d2e9.PNG)

**Comment by GillesBer** [comment]
This is not yet in v5, but there is already a PR for that
cf. https://github.com/MarimerLLC/csla/issues/1235

**Comment by BlagoCuljak** [comment]
@GillesBer sorry then!

**Comment by rockfordlhotka** [comment]
The next prerelease of v5 should be next week, at which point the new WPF and WinForms versions should be available.

**Comment by rockfordlhotka** [comment]
@BlagoCuljak please try the latest code in master - ProjectTracker should load and work now, as I've fixed that dependency issue.

Of course now that I say I've fixed it, something will go wrong, but that's just life 😎

**Comment by BlagoCuljak** [comment]
I have tried new version from couple hours ago, and still the same issue.


![package](https://user-images.githubusercontent.com/34435929/65016068-816d0880-d923-11e9-812b-78e80de61aa8.PNG)

**Comment by rockfordlhotka** [comment]
Thank you for pointing that out @BlagoCuljak - I keep forgetting to update the package references in the samples...

I'm doing that now, so all should be well within the next 15-30 minutes.

**Comment by BlagoCuljak** [comment]
@rockfordlhotka now it works like a charm... I see that URL to dataportal is now in Startup.cs, however, I have multiple users that connect to different dataportal, and I would only change that in .config.

Can we move it to external text file (.config, .ini), and how?

**Comment by rockfordlhotka** [comment]
Yes, read up on the .NET Core configuration subsystem. It is amazingly powerful!

To use it with CSLA, the best resource at the moment are the [configuration unit tests](https://github.com/MarimerLLC/csla/blob/master/Source/csla.netcore.test/Configuration/ReadConfigFromDotnetCoreSubsystemTests.cs). In general, configure the config subsystem and call `ConfigureCsla` to load the CSLA-specific settings.

```c#
      var config = new ConfigurationBuilder()
            .AddJsonFile("appsettings.dataportal.test.json")
            .Build()
            .ConfigureCsla();
```
